"""Seed content: the real syllabus structure, plus a starter question bank.

WHY THIS IS A DATA MODULE AND NOT A SCRIPT THAT INSERTS ROWS

Every value here is asserted by a test that runs without a database (see
``tests/test_seed_data.py``): unique codes, weights that sum plausibly, every
option set containing exactly one correct answer, every objective question
carrying an answer. A seed script that only runs against a live database cannot
be checked in CI, so its typos reach production as corrupt reference data - and
reference data is the one thing that is painful to correct after students have
progress attached to it.

THE SYLLABUS IS THE NEW SCHEME (2024). Paper names and groupings follow the
revised structure: Foundation 4 papers; Intermediate 6 papers across Groups I and
II; Final 6 papers. Weights are an editorial estimate of paper weightage, not an
ICAI-published figure - the chapter weighting the planner uses is a planning
input, and the planner is honest about being a plan.
"""

from __future__ import annotations

from typing import NamedTuple

SyllabusScheme = "NEW_2024"


class ChapterSeed(NamedTuple):
    code: str
    name: str
    weightage: int
    estimated_minutes: int


class SubjectSeed(NamedTuple):
    code: str
    name: str
    group: str | None
    paper_number: int
    weight: int
    chapters: tuple[ChapterSeed, ...]


class CourseSeed(NamedTuple):
    code: str
    name: str
    level: str
    description: str
    subjects: tuple[SubjectSeed, ...]


class OptionSeed(NamedTuple):
    label: str
    text: str
    is_correct: bool = False


class QuestionSeed(NamedTuple):
    """A question, keyed by subject and chapter CODE rather than by uuid.

    Ids are generated by the database, so a seed that hard-coded uuids would break
    the moment two environments were seeded independently - and the mock papers
    reference questions by id.
    """

    subject_code: str
    chapter_code: str
    text: str
    options: tuple[OptionSeed, ...]
    explanation: str
    difficulty: str = "MEDIUM"
    question_type: str = "MCQ"
    marks: int = 2


class MockSeed(NamedTuple):
    title: str
    course_code: str
    subject_code: str | None
    kind: str
    duration_min: int
    total_marks: int
    is_premium: bool
    chapter_codes: tuple[str, ...]


FOUNDATION = CourseSeed(
    code="CA_FOUNDATION",
    name="CA Foundation",
    level="FOUNDATION",
    description=(
        "Entry level of the CA course. Four papers, all descriptive and objective. "
        "Three attempts a year (January, May and September)."
    ),
    subjects=(
        SubjectSeed(
            code="FND_ACC",
            name="Accounting",
            group=None,
            paper_number=1,
            weight=25,
            chapters=(
                ChapterSeed("FND_ACC_01", "Theoretical Framework", 4, 180),
                ChapterSeed("FND_ACC_02", "Accounting Process", 5, 300),
                ChapterSeed("FND_ACC_03", "Depreciation and Inventory", 4, 240),
            ),
        ),
        SubjectSeed(
            code="FND_LAW",
            name="Business Laws",
            group=None,
            paper_number=2,
            weight=25,
            chapters=(
                ChapterSeed("FND_LAW_01", "Indian Contract Act, 1872", 5, 300),
                ChapterSeed("FND_LAW_02", "Sale of Goods Act, 1930", 3, 180),
            ),
        ),
        SubjectSeed(
            code="FND_QA",
            name="Quantitative Aptitude",
            group=None,
            paper_number=3,
            weight=25,
            chapters=(
                ChapterSeed("FND_QA_01", "Business Mathematics", 4, 240),
                ChapterSeed("FND_QA_02", "Statistical Description of Data", 3, 180),
            ),
        ),
        SubjectSeed(
            code="FND_ECO",
            name="Business Economics",
            group=None,
            paper_number=4,
            weight=25,
            chapters=(
                ChapterSeed("FND_ECO_01", "Nature and Scope of Business Economics", 3, 150),
                ChapterSeed("FND_ECO_02", "Theory of Demand and Supply", 4, 210),
            ),
        ),
    ),
)

INTERMEDIATE = CourseSeed(
    code="CA_INTERMEDIATE",
    name="CA Intermediate",
    level="INTERMEDIATE",
    description=(
        "Six papers in two groups. Pass mark is 40% per paper with 50% aggregate, "
        "and three attempts a year (January, May and September)."
    ),
    subjects=(
        SubjectSeed(
            code="INT_ACC",
            name="Advanced Accounting",
            group="GROUP_I",
            paper_number=1,
            weight=20,
            chapters=(
                ChapterSeed("INT_ACC_01", "Introduction to Accounting Standards", 3, 150),
                ChapterSeed("INT_ACC_02", "Revenue Recognition", 4, 240),
                ChapterSeed("INT_ACC_03", "Consolidated Financial Statements", 5, 360),
            ),
        ),
        SubjectSeed(
            code="INT_LAW",
            name="Corporate and Other Laws",
            group="GROUP_I",
            paper_number=2,
            weight=20,
            chapters=(
                ChapterSeed("INT_LAW_01", "The Companies Act, 2013", 5, 360),
                ChapterSeed("INT_LAW_02", "The Negotiable Instruments Act, 1881", 3, 180),
            ),
        ),
        SubjectSeed(
            code="INT_TAX",
            name="Taxation",
            group="GROUP_I",
            paper_number=3,
            weight=20,
            chapters=(
                ChapterSeed("INT_TAX_01", "Basic Concepts of Income Tax", 4, 240),
                ChapterSeed("INT_TAX_02", "Residence and Scope of Total Income", 4, 240),
                ChapterSeed("INT_TAX_03", "Goods and Services Tax", 4, 300),
            ),
        ),
        SubjectSeed(
            code="INT_COST",
            name="Cost and Management Accounting",
            group="GROUP_II",
            paper_number=4,
            weight=15,
            chapters=(
                ChapterSeed(
                    "INT_COST_01", "Introduction to Cost and Management Accounting", 4, 200
                ),
                ChapterSeed("INT_COST_02", "Material and Labour Cost", 4, 240),
            ),
        ),
        SubjectSeed(
            code="INT_AUD",
            name="Auditing and Ethics",
            group="GROUP_II",
            paper_number=5,
            weight=15,
            chapters=(
                ChapterSeed("INT_AUD_01", "Nature, Objective and Scope of Audit", 4, 200),
                ChapterSeed("INT_AUD_02", "Audit Documentation", 3, 150),
            ),
        ),
        SubjectSeed(
            code="INT_FMSM",
            name="Financial Management and Strategic Management",
            group="GROUP_II",
            paper_number=6,
            weight=10,
            chapters=(
                ChapterSeed("INT_FMSM_01", "Scope and Objectives of Financial Management", 4, 200),
                ChapterSeed("INT_FMSM_02", "Strategic Analysis: External Environment", 3, 180),
            ),
        ),
    ),
)

FINAL = CourseSeed(
    code="CA_FINAL",
    name="CA Final",
    level="FINAL",
    description=(
        "The final level. Two attempts a year from May 2026 - the January and "
        "September attempts were discontinued for Final, and two years of "
        "articleship are required."
    ),
    subjects=(
        SubjectSeed(
            code="FIN_FR",
            name="Financial Reporting",
            group="GROUP_I",
            paper_number=1,
            weight=20,
            chapters=(
                ChapterSeed(
                    "FIN_FR_01", "Framework for Preparation of Financial Statements", 3, 200
                ),
                ChapterSeed("FIN_FR_02", "Ind AS on Presentation", 5, 420),
                ChapterSeed("FIN_FR_03", "Business Combinations", 4, 360),
            ),
        ),
        SubjectSeed(
            code="FIN_AFM",
            name="Advanced Financial Management",
            group="GROUP_I",
            paper_number=2,
            weight=20,
            chapters=(
                ChapterSeed("FIN_AFM_01", "Financial Policy and Corporate Strategy", 4, 240),
                ChapterSeed("FIN_AFM_02", "Risk Management", 4, 300),
            ),
        ),
        SubjectSeed(
            code="FIN_AUD",
            name="Advanced Auditing, Assurance and Professional Ethics",
            group="GROUP_I",
            paper_number=3,
            weight=20,
            chapters=(
                ChapterSeed("FIN_AUD_01", "Standards on Auditing", 5, 360),
                ChapterSeed("FIN_AUD_02", "Professional Ethics", 4, 240),
            ),
        ),
        SubjectSeed(
            code="FIN_DT",
            name="Direct Tax Laws and International Taxation",
            group="GROUP_II",
            paper_number=4,
            weight=15,
            chapters=(
                ChapterSeed("FIN_DT_01", "Assessment of Various Entities", 5, 420),
                ChapterSeed("FIN_DT_02", "Transfer Pricing", 4, 300),
            ),
        ),
        SubjectSeed(
            code="FIN_IDT",
            name="Indirect Tax Laws",
            group="GROUP_II",
            paper_number=5,
            weight=15,
            chapters=(
                ChapterSeed("FIN_IDT_01", "GST: Supply and Levy", 5, 360),
                ChapterSeed("FIN_IDT_02", "Input Tax Credit", 4, 300),
            ),
        ),
        SubjectSeed(
            code="FIN_IBS",
            name="Integrated Business Solutions",
            group="GROUP_II",
            paper_number=6,
            weight=10,
            chapters=(ChapterSeed("FIN_IBS_01", "Multidisciplinary Case Study Approach", 5, 300),),
        ),
    ),
)

COURSES: tuple[CourseSeed, ...] = (FOUNDATION, INTERMEDIATE, FINAL)


# ------------------------------------------------------------------ questions
#
# Written for the platform, not lifted from ICAI papers - `source` says so, and
# the UI shows it. Anything attributed to a past attempt must also carry a
# disclaimer, so an unattributed question is the only kind that can be seeded
# without inventing provenance.

QUESTIONS: tuple[QuestionSeed, ...] = (
    QuestionSeed(
        subject_code="FND_ACC",
        chapter_code="FND_ACC_01",
        text=(
            "Which accounting concept requires that revenue be recognised when it is "
            "earned, and not when the cash for it is received?"
        ),
        options=(
            OptionSeed("A", "Cash basis of accounting"),
            OptionSeed("B", "Accrual basis of accounting", is_correct=True),
            OptionSeed("C", "Going concern basis"),
            OptionSeed("D", "Money measurement basis"),
        ),
        explanation=(
            "The accrual basis recognises revenue when the performance obligation is "
            "satisfied, regardless of when consideration moves. The cash basis is the "
            "opposite and is not permitted for companies."
        ),
        difficulty="EASY",
    ),
    QuestionSeed(
        subject_code="FND_ACC",
        chapter_code="FND_ACC_01",
        text="The accounting equation for a business at any point in time is:",
        options=(
            OptionSeed("A", "Assets = Liabilities - Capital"),
            OptionSeed("B", "Assets = Capital + Liabilities", is_correct=True),
            OptionSeed("C", "Capital = Assets + Liabilities"),
            OptionSeed("D", "Assets + Capital = Liabilities"),
        ),
        explanation=(
            "Every asset is financed either by the owner (capital) or by a third "
            "party (liability). Assets = Capital + Liabilities restates the same "
            "identity as Capital = Assets - Liabilities."
        ),
        difficulty="EASY",
    ),
    QuestionSeed(
        subject_code="FND_ACC",
        chapter_code="FND_ACC_03",
        text=(
            "A machine costing Rs 5,00,000 is depreciated under the straight line "
            "method over 10 years with no residual value. What is the book value "
            "after the third year?"
        ),
        options=(
            OptionSeed("A", "Rs 3,50,000", is_correct=True),
            OptionSeed("B", "Rs 3,00,000"),
            OptionSeed("C", "Rs 4,00,000"),
            OptionSeed("D", "Rs 2,50,000"),
        ),
        explanation=(
            "Annual depreciation is 5,00,000 / 10 = 50,000. After three years the "
            "accumulated depreciation is 1,50,000, leaving 3,50,000."
        ),
    ),
    QuestionSeed(
        subject_code="FND_ACC",
        chapter_code="FND_ACC_03",
        text=(
            "Under the FIFO method of inventory valuation, the cost of goods sold "
            "is computed using:"
        ),
        options=(
            OptionSeed("A", "The most recent purchase prices"),
            OptionSeed("B", "The earliest purchase prices", is_correct=True),
            OptionSeed("C", "The weighted average price for the period"),
            OptionSeed("D", "The standard price fixed by management"),
        ),
        explanation=(
            "FIFO assumes the earliest units acquired are sold first, so cost of goods "
            "sold reflects the oldest prices and closing inventory reflects the newest. "
            "(C) describes the weighted average method."
        ),
    ),
    QuestionSeed(
        subject_code="FND_LAW",
        chapter_code="FND_LAW_01",
        text=(
            "An agreement without consideration is void, with exceptions. Which of the "
            "following is NOT one of them?"
        ),
        options=(
            OptionSeed(
                "A", "A written and registered promise made out of natural love and affection"
            ),
            OptionSeed(
                "B", "A promise to compensate for a past voluntary act done for the promisor"
            ),
            OptionSeed("C", "A promise to pay a time-barred debt, made in writing and signed"),
            # The question asks which is NOT an exception, so the answer is the one
            # without the formality Section 25 requires.
            OptionSeed(
                "D", "A promise made orally to deliver goods at a future date", is_correct=True
            ),
        ),
        explanation=(
            "Section 25 of the Indian Contract Act, 1872 lists the exceptions, and each "
            "of them is subject to a formality - written and registered, or written and "
            "signed. A bare oral promise is not one of them."
        ),
    ),
    QuestionSeed(
        subject_code="FND_LAW",
        chapter_code="FND_LAW_02",
        text=(
            "Under the Sale of Goods Act, 1930, in a contract for sale of specific goods "
            "which have, without the knowledge of the seller, perished at the time the "
            "contract was made, the contract is:"
        ),
        options=(
            OptionSeed("A", "Voidable at the option of the buyer"),
            OptionSeed("B", "Void", is_correct=True),
            OptionSeed("C", "Valid, with the seller liable in damages"),
            OptionSeed("D", "Unenforceable until the goods are replaced"),
        ),
        explanation=(
            "Section 7 provides that where the goods have perished before the contract "
            "was made, the contract is void - there is no agreement over a subject "
            "matter that does not exist. It is not merely voidable."
        ),
    ),
    QuestionSeed(
        subject_code="FND_QA",
        chapter_code="FND_QA_01",
        text=(
            "A sum of Rs 1,00,000 is invested at 10% per annum compounded annually. "
            "What is the amount after two years?"
        ),
        options=(
            OptionSeed("A", "Rs 1,20,000"),
            OptionSeed("B", "Rs 1,21,000", is_correct=True),
            OptionSeed("C", "Rs 1,22,100"),
            OptionSeed("D", "Rs 1,10,000"),
        ),
        explanation=(
            "1,00,000 x 1.10 x 1.10 = 1,21,000. The Rs 1,000 difference from the simple "
            "interest answer (1,20,000) is interest on the first year's interest - which "
            "is exactly why compounding matters over a long horizon."
        ),
    ),
    QuestionSeed(
        subject_code="FND_QA",
        chapter_code="FND_QA_02",
        text="A distribution in which the mean, median and mode are all equal is:",
        options=(
            OptionSeed("A", "Positively skewed"),
            OptionSeed("B", "Negatively skewed"),
            OptionSeed("C", "Symmetrical", is_correct=True),
            OptionSeed("D", "Leptokurtic"),
        ),
        explanation=(
            "Symmetry makes the three measures coincide. Skewness separates them: in a "
            "positively skewed distribution the mean is pulled above the median."
        ),
        difficulty="EASY",
    ),
    QuestionSeed(
        subject_code="FND_ECO",
        chapter_code="FND_ECO_02",
        text="The demand curve facing a firm in perfect competition is:",
        options=(
            OptionSeed("A", "Downward sloping, same as the market demand curve"),
            OptionSeed("B", "Horizontal at the prevailing market price", is_correct=True),
            OptionSeed("C", "Vertical, because output is fixed in the short run"),
            OptionSeed("D", "U-shaped, because of diminishing returns"),
        ),
        explanation=(
            "A price taker has no influence over price, so it can sell any quantity at "
            "the market price: perfectly elastic demand. The downward-sloping curve "
            "belongs to the market or to an imperfect competitor."
        ),
    ),
    QuestionSeed(
        subject_code="INT_ACC",
        chapter_code="INT_ACC_01",
        text=(
            "Which of the following is NOT a qualitative characteristic of useful "
            "financial information under the Conceptual Framework?"
        ),
        options=(
            OptionSeed("A", "Relevance"),
            OptionSeed("B", "Faithful representation"),
            OptionSeed("C", "Conservatism", is_correct=True),
            OptionSeed("D", "Comparability"),
        ),
        explanation=(
            "Prudence is a support to faithful representation, but Conservatism - "
            "deliberately understating assets or overstating liabilities - is explicitly "
            "incompatible with neutrality, so it is not a qualitative characteristic."
        ),
    ),
    QuestionSeed(
        subject_code="INT_ACC",
        chapter_code="INT_ACC_02",
        text=("Under Ind AS 115, revenue from a contract with a customer is recognised when:"),
        options=(
            OptionSeed("A", "The invoice is raised"),
            OptionSeed("B", "Payment is received"),
            OptionSeed("C", "The performance obligation is satisfied", is_correct=True),
            OptionSeed("D", "The contract is signed"),
        ),
        explanation=(
            "Ind AS 115 replaced the risk-and-rewards transfer test with control. "
            "Invoicing and collection are cash events, not performance."
        ),
    ),
    QuestionSeed(
        subject_code="INT_ACC",
        chapter_code="INT_ACC_03",
        text=("In a consolidated balance sheet, the non-controlling interest is presented:"),
        options=(
            OptionSeed("A", "As a liability, because it is owed to outsiders"),
            OptionSeed("B", "Within equity, separately from the parent's equity", is_correct=True),
            OptionSeed("C", "As a deduction from goodwill"),
            OptionSeed("D", "As a note only, without a balance sheet line"),
        ),
        explanation=(
            "Ind AS 110 requires non-controlling interests to be presented within "
            "equity and separately from the equity of the owners of the parent. Calling "
            "it a liability would misstate the group's gearing."
        ),
    ),
    QuestionSeed(
        subject_code="INT_LAW",
        chapter_code="INT_LAW_01",
        text=(
            "Under the Companies Act, 2013, the minimum number of directors in a public company is:"
        ),
        options=(
            OptionSeed("A", "Two"),
            OptionSeed("B", "Three", is_correct=True),
            OptionSeed("C", "Seven"),
            OptionSeed("D", "One"),
        ),
        explanation=(
            "Section 149 requires at least three directors in a public company, two in "
            "a private company and one in a One Person Company. Seven is the minimum "
            "number of MEMBERS for a public company, not directors."
        ),
        difficulty="EASY",
    ),
    QuestionSeed(
        subject_code="INT_LAW",
        chapter_code="INT_LAW_02",
        text=("A cheque marked 'account payee only' and crossed can be:"),
        options=(
            OptionSeed("A", "Transferred by mere delivery"),
            OptionSeed("B", "Collected only for the payee's account", is_correct=True),
            OptionSeed("C", "Endorsed in favour of any holder in due course"),
            OptionSeed("D", "Negotiated to a third party without endorsement"),
        ),
        explanation=(
            "Section 130 of the Negotiable Instruments Act, 1881 makes a crossing a "
            "direction to the collecting banker: the proceeds go to the payee's "
            "account. The statutory protection that follows is why the crossing exists."
        ),
    ),
    QuestionSeed(
        subject_code="INT_TAX",
        chapter_code="INT_TAX_01",
        text=(
            "Under the Income-tax Act, 1961, the year in which income is earned is called "
            "the previous year, and the year in which it is assessed is the:"
        ),
        options=(
            OptionSeed("A", "Financial year"),
            OptionSeed("B", "Assessment year", is_correct=True),
            OptionSeed("C", "Accounting year"),
            OptionSeed("D", "Taxable year"),
        ),
        explanation=(
            "Section 2(9) defines the assessment year as the twelve months beginning on "
            "1 April following the previous year. The two are distinct and the exam "
            "regularly tests the distinction."
        ),
        difficulty="EASY",
    ),
    QuestionSeed(
        subject_code="INT_TAX",
        chapter_code="INT_TAX_02",
        text=("An individual who is a resident and ordinarily resident in India is taxed on:"),
        options=(
            OptionSeed("A", "Indian income only"),
            OptionSeed("B", "Income received in India only"),
            OptionSeed("C", "Global income", is_correct=True),
            OptionSeed("D", "Income accruing in India only"),
        ),
        explanation=(
            "Residence and ordinary residence determine the SCOPE: an ROR is taxed on "
            "global income; a resident but not ordinarily resident is taxed on Indian "
            "income plus foreign income from a business controlled in India."
        ),
    ),
    QuestionSeed(
        subject_code="INT_TAX",
        chapter_code="INT_TAX_03",
        text="Goods and Services Tax in India is a tax on:",
        options=(
            OptionSeed("A", "Manufacture only"),
            OptionSeed("B", "Sale only"),
            OptionSeed("C", "Supply", is_correct=True),
            OptionSeed("D", "Import only"),
        ),
        explanation=(
            "The taxable event under GST is 'supply' - a wider concept than manufacture, "
            "sale or import, defined in Section 7 of the CGST Act. That breadth is what "
            "made the earlier cascading of taxes removable."
        ),
    ),
    QuestionSeed(
        subject_code="INT_COST",
        chapter_code="INT_COST_01",
        text=(
            "Which of the following costs is NOT included in the valuation of closing "
            "inventory of finished goods under the cost accounts?"
        ),
        options=(
            OptionSeed("A", "Direct material"),
            OptionSeed("B", "Direct labour"),
            OptionSeed("C", "Factory overheads absorbed"),
            OptionSeed("D", "Selling and distribution overheads", is_correct=True),
        ),
        explanation=(
            "Inventory is valued at cost of production. Selling and distribution "
            "overheads are absorbed only for the cost of sales, not for inventory "
            "valuation."
        ),
    ),
    QuestionSeed(
        subject_code="INT_COST",
        chapter_code="INT_COST_02",
        text=(
            "Under the economic order quantity model, the total inventory cost is minimised where:"
        ),
        options=(
            OptionSeed("A", "Ordering cost equals carrying cost", is_correct=True),
            OptionSeed("B", "Ordering cost is at its minimum"),
            OptionSeed("C", "Carrying cost is at its minimum"),
            OptionSeed("D", "The purchase price is at its lowest"),
        ),
        explanation=(
            "EOQ balances the two opposing costs: ordering cost falls as orders get "
            "larger, carrying cost rises. Their intersection is the minimum of the "
            "total - which is also where the two are equal."
        ),
    ),
    QuestionSeed(
        subject_code="INT_AUD",
        chapter_code="INT_AUD_01",
        text=("The primary objective of an audit of financial statements is to:"),
        options=(
            OptionSeed("A", "Detect all fraud and error"),
            OptionSeed(
                "B",
                "Express an opinion on whether the statements are free from material misstatement",
                is_correct=True,
            ),
            OptionSeed("C", "Guarantee the accuracy of every transaction"),
            OptionSeed("D", "Report to the tax authorities"),
        ),
        explanation=(
            "An audit provides reasonable, not absolute, assurance. No auditor detects "
            "every fraud, and an engagement letter promising otherwise would be both "
            "impossible and a liability."
        ),
        difficulty="EASY",
    ),
    QuestionSeed(
        subject_code="INT_AUD",
        chapter_code="INT_AUD_02",
        text=("The auditor's working papers are the property of:"),
        options=(
            OptionSeed("A", "The client, because they relate to the client's records"),
            OptionSeed("B", "The auditor", is_correct=True),
            OptionSeed("C", "The shareholders"),
            OptionSeed("D", "The income tax department"),
        ),
        explanation=(
            "Working papers are the auditor's property and their confidentiality is a "
            "professional duty; the client has a right of access, not ownership."
        ),
    ),
    QuestionSeed(
        subject_code="INT_FMSM",
        chapter_code="INT_FMSM_01",
        text="The primary objective of financial management is to:",
        options=(
            OptionSeed("A", "Maximise the number of shares issued"),
            OptionSeed("B", "Maximise shareholder wealth", is_correct=True),
            OptionSeed("C", "Minimise the tax payable in every year"),
            OptionSeed("D", "Maximise current period profit"),
        ),
        explanation=(
            "Wealth maximisation accounts for the timing and risk of cash flows, which "
            "profit maximisation does not. A decision can raise this year's profit and "
            "destroy value - a point the paper tests repeatedly."
        ),
    ),
    QuestionSeed(
        subject_code="FIN_FR",
        chapter_code="FIN_FR_01",
        text=("Under Ind AS, an asset is recognised when:"),
        options=(
            OptionSeed("A", "Cost has been incurred"),
            OptionSeed(
                "B",
                "There is a present economic resource controlled as a result of a past event",
                is_correct=True,
            ),
            OptionSeed("C", "It has been paid for in cash"),
            OptionSeed("D", "Management intends to use it within a year"),
        ),
        explanation=(
            "Control of a present economic resource arising from a past event is the "
            "definition in the Conceptual Framework. Incurring cost is not sufficient - "
            "research expenditure is an expense for that reason."
        ),
    ),
    QuestionSeed(
        subject_code="FIN_FR",
        chapter_code="FIN_FR_03",
        text=("Under Ind AS 103, goodwill arising in a business combination is:"),
        options=(
            OptionSeed("A", "Amortised over its useful life"),
            OptionSeed("B", "Tested for impairment annually", is_correct=True),
            OptionSeed("C", "Written off against reserves immediately"),
            OptionSeed("D", "Amortised over a period not exceeding ten years"),
        ),
        explanation=(
            "Goodwill is not amortised under Ind AS. It is tested for impairment at "
            "least annually, and more often when there is an indication."
        ),
    ),
    QuestionSeed(
        subject_code="FIN_DT",
        chapter_code="FIN_DT_02",
        text=(
            "The arm's length principle in transfer pricing requires that the price "
            "charged between associated enterprises be:"
        ),
        options=(
            OptionSeed("A", "The price at which the goods were actually purchased"),
            OptionSeed(
                "B",
                "The price that would have been charged between independent parties",
                is_correct=True,
            ),
            OptionSeed("C", "The price approved by the government"),
            OptionSeed("D", "The average of all intra-group prices"),
        ),
        explanation=(
            "The arm's length price is a hypothetical one between unrelated parties. "
            "The methods prescribed in the rules are all ways of estimating it; none of "
            "them makes the agreed price determinative."
        ),
    ),
    QuestionSeed(
        subject_code="FIN_IDT",
        chapter_code="FIN_IDT_02",
        text=("Input tax credit is available to a registered person in respect of:"),
        options=(
            OptionSeed("A", "Any goods purchased, regardless of their use"),
            OptionSeed(
                "B",
                "Goods and services used in the course or furtherance of business",
                is_correct=True,
            ),
            OptionSeed("C", "Goods used for personal consumption of the proprietor"),
            OptionSeed("D", "Goods that are lost, stolen or destroyed"),
        ),
        explanation=(
            "Section 16 of the CGST Act restricts the credit to inputs used in the "
            "course or furtherance of business, and Section 17 denies it on blocked "
            "credits including personal consumption."
        ),
    ),
    QuestionSeed(
        subject_code="FIN_AUD",
        chapter_code="FIN_AUD_02",
        text=("A chartered accountant who holds a substantial interest in a company is:"),
        options=(
            OptionSeed("A", "Permitted to audit it if the interest is disclosed to the board"),
            OptionSeed("B", "Disqualified from being appointed as its auditor", is_correct=True),
            OptionSeed(
                "C", "Permitted to audit it if the interest is worth less than ten lakh rupees"
            ),
            OptionSeed("D", "Permitted to audit it if the board gives prior written approval"),
        ),
        explanation=(
            "Section 141 disqualifies an auditor who is indebted, or has a substantial "
            "interest in the company, regardless of disclosure or consent - independence "
            "cannot be licensed by the client."
        ),
    ),
)


MOCKS: tuple[MockSeed, ...] = (
    MockSeed(
        title="Foundation Paper 1 - Accounting: chapter practice",
        course_code="CA_FOUNDATION",
        subject_code="FND_ACC",
        kind="CHAPTER",
        duration_min=30,
        total_marks=10,
        is_premium=False,
        chapter_codes=("FND_ACC_01", "FND_ACC_03"),
    ),
    MockSeed(
        title="Intermediate Tax - previous attempt paper (sample)",
        course_code="CA_INTERMEDIATE",
        subject_code="INT_TAX",
        kind="PREVIOUS_PAPER",
        duration_min=60,
        total_marks=20,
        is_premium=False,
        chapter_codes=("INT_TAX_01", "INT_TAX_02", "INT_TAX_03"),
    ),
    MockSeed(
        title="Final - Full length paper 1: Financial Reporting",
        course_code="CA_FINAL",
        subject_code="FIN_FR",
        kind="FULL_LENGTH",
        duration_min=180,
        total_marks=60,
        is_premium=True,
        chapter_codes=("FIN_FR_01", "FIN_FR_03", "FIN_AFM_01", "FIN_AUD_01"),
    ),
)


#: Published exam attempts.
#:
#: A SESSION HERE MEANS A MONTH, NOT A LEVEL. `exam_sessions` is unique on
#: (year, month), so it cannot hold "Final - May 2026" and "Intermediate - May
#: 2026" as two rows. That is a real limitation rather than a stylistic choice:
#: Final now runs only in May and November while Intermediate also runs in
#: January, so a per-level calendar needs a `level` column and a wider unique key.
#: Recorded in the build audit; until then the label names the month, and the
#: planner takes the student's own exam date anyway.
#:
#: `exam_start_date` is NULL on purpose: ICAI publishes the calendar separately,
#: and a countdown computed from an invented date is worse than no countdown.
EXAM_SESSIONS: tuple[tuple[int, str, str], ...] = (
    (2026, "MAY", "May 2026"),
    (2026, "NOVEMBER", "November 2026"),
    (2027, "MAY", "May 2027"),
)


def chapter_by_code() -> dict[str, ChapterSeed]:
    return {
        chapter.code: chapter
        for course in COURSES
        for subject in course.subjects
        for chapter in subject.chapters
    }


def subject_by_code() -> dict[str, SubjectSeed]:
    return {subject.code: subject for course in COURSES for subject in course.subjects}


def course_of_subject(subject_code: str) -> CourseSeed:
    for course in COURSES:
        for subject in course.subjects:
            if subject.code == subject_code:
                return course
    raise KeyError(subject_code)
