"""campus tools and review state

Revision ID: 6c3f7b0a0c13
Revises: 0013_splits_payments_notices
Create Date: 2026-09-26 20:02:51.051018

Blueprint v3 §2: Alembic migrations.

REMINDER - autogenerate does not cover everything:
  * expression indexes (the GIN tsvector index) are invisible to it
  * renamed columns appear as drop + add, which LOSES DATA
  * CHECK constraint changes are frequently missed
Always read the generated diff before applying it.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6c3f7b0a0c13"
down_revision: str | None = "0013_splits_payments_notices"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiments",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "variants",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'["A", "B"]\'::jsonb'),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_experiment_key"),
    )
    op.create_table(
        "glossary_entries",
        sa.Column("term", sa.String(length=120), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column(
            "source", sa.String(length=40), server_default=sa.text("'editor'"), nullable=False
        ),
        sa.Column("published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source IN ('platform','editor')", name="ck_glossary_source"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("term", name="uq_glossary_term"),
    )
    op.create_index("idx_glossary_published", "glossary_entries", ["published"], unique=False)
    op.create_table(
        "calendar_events",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "source", sa.String(length=20), server_default=sa.text("'student'"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source = 'student'", name="ck_calendar_source_is_student"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_calendar_events_user", "calendar_events", ["user_id", "starts_at"], unique=False
    )
    op.create_table(
        "experiment_assignments",
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("variant", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("experiment_id", "user_id", name="uq_experiment_assignment"),
    )
    op.create_table(
        "formula_entries",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("subject_label", sa.String(length=80), nullable=True),
        sa.Column("published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_formula_entries_published", "formula_entries", ["published"], unique=False)
    op.create_table(
        "forum_threads",
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("subject_label", sa.String(length=80), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_forum_threads_created", "forum_threads", ["created_at"], unique=False)
    op.create_table(
        "marketplace_listings",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("plan_code", sa.String(length=40), nullable=True),
        sa.Column("price_paise", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("takes_payment", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_paise IS NULL OR price_paise >= 0", name="ck_marketplace_price_non_negative"
        ),
        sa.CheckConstraint("takes_payment = false", name="ck_marketplace_does_not_charge"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_marketplace_active", "marketplace_listings", ["active"], unique=False)
    op.create_table(
        "mentorship_requests",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default=sa.text("'OPEN'"), nullable=False),
        sa.Column("mentor_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('OPEN','MATCHED','CLOSED')", name="ck_mentorship_status"),
        sa.ForeignKeyConstraint(["mentor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_mentorship_student", "mentorship_requests", ["student_id", "created_at"], unique=False
    )
    op.create_table(
        "pomodoro_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "reported_by_client", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("minutes BETWEEN 1 AND 120", name="ck_pomodoro_minutes"),
        sa.CheckConstraint("reported_by_client = true", name="ck_pomodoro_is_self_reported"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_pomodoro_user", "pomodoro_sessions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "study_groups",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "support_tickets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=140), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'OPEN'"), nullable=False),
        sa.Column("email_sent", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('OPEN','ACKNOWLEDGED','CLOSED')", name="ck_support_status"),
        sa.CheckConstraint("email_sent = false", name="ck_support_does_not_send_email"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_support_tickets_status", "support_tickets", ["status", "created_at"], unique=False
    )
    op.create_table(
        "forum_posts",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["forum_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_forum_posts_thread", "forum_posts", ["thread_id", "created_at"], unique=False
    )
    op.create_table(
        "study_group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), server_default=sa.text("'MEMBER'"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('OWNER','MEMBER')", name="ck_study_group_member_role"),
        sa.ForeignKeyConstraint(["group_id"], ["study_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "user_id", name="uq_study_group_member"),
    )
    op.create_index(
        "idx_study_group_members_user", "study_group_members", ["user_id"], unique=False
    )
    op.create_table(
        "exam_mode_sittings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column(
            "hides_answers_until_submit",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("camera_used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("camera_used = false", name="ck_exam_mode_no_camera"),
        sa.CheckConstraint("hides_answers_until_submit = true", name="ck_exam_mode_hides_answers"),
        sa.ForeignKeyConstraint(["attempt_id"], ["mock_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", name="uq_exam_mode_attempt"),
    )
    op.create_table(
        "proctor_events",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('TAB_HIDDEN','TAB_VISIBLE','WINDOW_BLUR','COPY_ATTEMPT','PASTE_ATTEMPT')",
            name="ck_proctor_event_type",
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["mock_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_proctor_events_attempt", "proctor_events", ["attempt_id", "created_at"], unique=False
    )
    op.add_column(
        "questions",
        sa.Column(
            "review_state",
            sa.String(length=32),
            server_default=sa.text("'CURRENT'"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "ck_questions_review_state",
        "questions",
        "review_state IN ('CURRENT','VERIFICATION_REQUIRED','NEEDS_UPDATE','PENDING_ADMIN_REVIEW')",
    )
    # Platform glossary. These describe the product. They are not statutes.
    op.execute(
        """
        INSERT INTO glossary_entries (id, term, definition, source, published, created_at, updated_at)
        VALUES
        (gen_random_uuid(), 'Mock exam',
         'A timed paper on this platform. The score is this paper, not an ICAI result.',
         'platform', true, now(), now()),
        (gen_random_uuid(), 'Historical question',
         'A published question kept with its Finance Act year and a disclaimer. The answer is not rewritten when the law moves.',
         'platform', true, now(), now()),
        (gen_random_uuid(), 'Spaced revision',
         'Cards this platform schedules from your own practice. The interval is a study aid, not a prediction of the exam.',
         'platform', true, now(), now()),
        (gen_random_uuid(), 'Study group',
         'A list of display names. Email addresses are not shown to other members.',
         'platform', true, now(), now()),
        (gen_random_uuid(), 'Exam mode',
         'A record that you sat a mock with answers hidden until submit. It does not open a camera or lock the browser.',
         'platform', true, now(), now())
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_questions_review_state", "questions", type_="check")
    op.drop_column("questions", "review_state")
    op.drop_index("idx_proctor_events_attempt", table_name="proctor_events")
    op.drop_table("proctor_events")
    op.drop_table("exam_mode_sittings")
    op.drop_index("idx_study_group_members_user", table_name="study_group_members")
    op.drop_table("study_group_members")
    op.drop_index("idx_forum_posts_thread", table_name="forum_posts")
    op.drop_table("forum_posts")
    op.drop_index("idx_support_tickets_status", table_name="support_tickets")
    op.drop_table("support_tickets")
    op.drop_table("study_groups")
    op.drop_index("idx_pomodoro_user", table_name="pomodoro_sessions")
    op.drop_table("pomodoro_sessions")
    op.drop_index("idx_mentorship_student", table_name="mentorship_requests")
    op.drop_table("mentorship_requests")
    op.drop_index("idx_marketplace_active", table_name="marketplace_listings")
    op.drop_table("marketplace_listings")
    op.drop_index("idx_forum_threads_created", table_name="forum_threads")
    op.drop_table("forum_threads")
    op.drop_index("idx_formula_entries_published", table_name="formula_entries")
    op.drop_table("formula_entries")
    op.drop_table("experiment_assignments")
    op.drop_index("idx_calendar_events_user", table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index("idx_glossary_published", table_name="glossary_entries")
    op.drop_table("glossary_entries")
    op.drop_table("experiments")
    # ### end Alembic commands ###
